version: '3.9'
services:
  db:
    image: postgres:16
    container_name: fs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: futurosimples
    ports: ["5432:5432"]
    volumes:
      - fs_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fs_redis
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  fs_db_data:
